### ISSUE TITLE
Question: react-native wrapper for iOS & Android sdks? 

### ISSUE THREAD

**Issue by kumarpatel** [Webtrekk/webtrekk-android-sdk#1]
is there one in the making or will there be one in the near future?

**Comment by arsen-vartbaronov** [comment]
@olebahlmann Can you provide information about plans for react-native?

**Comment by kumarpatel** [comment]
If a RN wrapper is in the making, I'd love to start using your WIP wrappper and perhaps contribute to it.
If there's no plans to support a RN wrapper, I'll start making one myself.
Thought I'd check in before I started making one ¯\_(ツ)_/¯

**Comment by arsen-vartbaronov** [comment]
@kumarpatel I understand you. I don't have information that such wrapper is planed, but let's wait for reply from @olebahlmann, as he is more aware about plans.

**Comment by arsen-vartbaronov** [comment]
@kumarpatel. Please note that I made force push for this repository. So if you will do development, please update your local copy.

**Comment by arsen-vartbaronov** [comment]
@olebahlmann do you have any news for this issue?

**Comment by kumarpatel** [comment]
Question was already answered here
https://github.com/Webtrekk/webtrekk-ios-sdk/issues/14

**Comment by arsen-vartbaronov** [comment]
@kumarpatel Thanks. In that case I close this issue and open another one as soon as there is Pull request to merge.
