### ISSUE TITLE
Tracking custom TrackingParameter before tracking a page results in missing screen size

### ISSUE THREAD

**Issue by ntorring** [Webtrekk/webtrekk-android-sdk#27]
In our application we wish to send a custom "app_open" event upon startup. We are doing this from our Main activity, and we have automatic tracking turned off.
In the log we can see that the generated URL has screen dimensions set to **null**, and the event appears to get ignored by the backend. If we just call `webtrekk.track();` once, all subsequent tracking calls include the correct screen dimensions.
Here is a snippet of my code:
`webtrekk.setCustomPageName("MainActivity");`
~~`webtrekk.track();`~~
`TrackingParameter tp = new TrackingParameter();`
`tp.add(TrackingParameter.Parameter.ACTION_NAME, "app_open"));`
`webtrekk.track(tp);`

This is part of the output URL parameters:
**/wt?p=4110,MainActivity,0,null,32,0,1543320567931,0,0,0&eid=...**

Given the design of the application, we are not interested in tracking the "MainActivity" as a page view!

**Comment by Neno0o** [comment]
If you only want to send the "app_open" event as a custom param, then you don't need to call `webtrekk.track()`at the beginning, you just need to pass your custom params to `webtrekk.track(customParams)`.

Then, it should be look like this:
`webtrekk.setCustomPageName("MainActivity");`
`TrackingParameter tp = new TrackingParameter();`
`tp.add(TrackingParameter.Parameter.ACTION_NAME, "app_open"));`
`webtrekk.track(tp);`

Regarding the screen dimensions are set to null, it seems a minor bug in the SDK. You can expect a quick fix release soon.

**Comment by ntorring** [comment]
That is actually what I'm doing, I just forgot to remove the `webtrekk.track();` line from my example (It is my workaround, to get the SDK to set the screen dimensions)
